const express = require('express');
const cors = require('cors');
const path = require('path');
const fs = require('fs');
const https = require('https');
const http = require('http');

const app = express();
const PORT = process.env.PORT || 38472;

app.use(cors());

// Security headers required for Microsoft Word / Office WebView2 iframe embedding
app.use((req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('X-Frame-Options', 'ALLOWALL');
  res.setHeader(
    'Content-Security-Policy',
    "default-src 'self' 'unsafe-inline' 'unsafe-eval' " +
    "https://appsforoffice.microsoft.com " +
    "https://*.officeapps.live.com " +
    "https://*.office.com " +
    "https://*.microsoft.com " +
    "http://localhost:* https://localhost:*;"
  );
  next();
});

// Serve static files from the src/ directory
app.use(express.static(path.join(__dirname, 'src')));

app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'src', 'index.html'));
});

// Health check endpoint – used by ABNT.ps1 to verify the server is responsive
app.get('/health', (req, res) => {
  res.json({ status: 'ok', port: PORT, timestamp: Date.now() });
});

/**
 * Attempts to load SSL certificates generated by office-addin-dev-certs.
 * Falls back to plain HTTP if certificates are not found.
 * @returns {{ key: Buffer, cert: Buffer } | null}
 */
function getSslOptions() {
  const certDir = path.join(process.env.USERPROFILE || process.env.HOME || '', '.office-addin-dev-certs');
  const keyPath = path.join(certDir, 'localhost.key');
  const certPath = path.join(certDir, 'localhost.crt');

  if (fs.existsSync(keyPath) && fs.existsSync(certPath)) {
    try {
      return {
        key: fs.readFileSync(keyPath),
        cert: fs.readFileSync(certPath),
      };
    } catch (e) {
      console.log('Warning: could not read SSL certificates:', e.message);
    }
  }
  return null;
}

const sslOptions = getSslOptions();
const server = sslOptions ? https.createServer(sslOptions, app) : http.createServer(app);
const protocol = sslOptions ? 'https' : 'http';

server.on('error', (err) => {
  if (err.code === 'EADDRINUSE') {
    console.error(`\n⚠️ Port ${PORT} is already in use.`);
  } else {
    console.error('Server error:', err.message);
  }
});

server.listen(PORT, '0.0.0.0', () => {
  console.log(`\n======================================================`);
  console.log(`🚀 ABNT SERVER READY FOR MICROSOFT WORD:`);
  console.log(`👉 ${protocol}://localhost:${PORT}/index.html`);
  console.log(`======================================================\n`);
});
